# Generated by Django 4.0.4 on 2022-05-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ipInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_time', models.DateTimeField(verbose_name='datatime connected')),
                ('server_ipv4', models.CharField(max_length=15)),
                ('usr_ipv4', models.CharField(max_length=15)),
            ],
        ),
    ]
